In [1]:
# 1. Create a null vector of size 10 but the fifth value which is 1.

# Solution :-

import numpy as np 

null_vector = np.zeros(10) 
null_vector[4] = 1 
print('The Required answer is : ',null_vector)

The Required answer is :  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [2]:
# 2.Create a vector with values ranging from 10 to 49.
import numpy as np

vector = np.arange(10,50)
print('The required vector is : ',vector)

The required vector is :  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np

matrix = np.array([[0,1,2],[3,4,5],[6,7,8]])

print('The 3x3 matrix is : ' ,matrix)

The 3x3 matrix is :  [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np 

list_1 = [1,2,0,0,4,0] 

print("Non-zero elements indices:") 

result = np.nonzero(list_1) 

print('The result is : ' ,result)

Non-zero elements indices:
The result is :  (array([0, 1, 4], dtype=int64),)


In [5]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.

import numpy as np 

array = np.random.randint(low=1, high=150, size=(10, 10)) 

print("The 10x10 array of random values is:\n") 
print(array) 

print("\nThe minimum value in the array is:", np.min(array)) 
print("The maximum value in the array is:", np.max(array))

The 10x10 array of random values is:

[[ 94  27  71  89  98 103 148  81  37 123]
 [ 88  62   4  96   1   3   5 139  45   1]
 [ 90  66  41 119 133  85 116   2  86 101]
 [ 12  36 129 106  42  31  50 139 102  24]
 [ 49  78 133 108  38  19  76  28  65  13]
 [124 132 145  16   6  70  82  84  54   3]
 [ 14  59  91 100  22 118  58 140 108  21]
 [ 84  63  51 142  37  75  34  58  80  14]
 [ 55 126  91 112  28 148 137 123 126   4]
 [140 111 104  65  37  49  38   5 117 106]]

The minimum value in the array is: 1
The maximum value in the array is: 148


In [6]:
# 6. Create a random vector of size 30 and find the mean value.


import numpy as np

rand_vector = np.random.randint(1,100,30)

mean_value = np.mean(rand_vector)

print("Random vector is :", rand_vector)
print("Mean value of the vector is :", mean_value)

Random vector is : [10 71 15  5 81 54 49 84 99 10 48 83 58  6 12 24 76 85 28 22 70 64 19 10
 62  2  1 17 16 11]
Mean value of the vector is : 39.733333333333334
